version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: tabgeni-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_DATABASE: tabgeni

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tabgeni-app
    restart: always
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/tabgeni
      - PORT=3001
      - NEXT_PUBLIC_API_URL=http://localhost:3001
    depends_on:
      - mongodb
    volumes:
      - ./uploads:/app/uploads

volumes:
  mongodb_data:
